title: Intensifier Use By Gender Analysis
description: The page of the Wugs team for the analysis project
show_downloads: True
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - REPORT.md

theme: jekyll-theme-minimal
